mkdir learning_python_hard_way
cd learning_python_hard_way
cd ../.
cd changeCalculator
python calculator.py
cd changeCalculator
python changeCalculator
python calculator.py
calculator.py
python calculator.py
cd changeCalculator
python calculator.py
cd changeCalculator
python calculator.py
cd changeCalculator
python calculator.py
cd changeCalculator
python calculator.py
cd changeCalculator
python calulator.py
python calculator.py
cd changeCalculator
python calculator.py
cd changeCalculator
python calculator.py
cd changeCalculator
python calculator.py
mkdir highLowGame
cd highLowGame
python game.py
cd highLowGame
python game.py
cd ../
mkdir rightTriangleChecker
cd rightTriangleChecker
python rightTriangle.py
cd rightTriangleChecker
python rightTriangle.py
python rightTriangle.puy
python rightTriangle.py
cd rightTriangleChecker
python rightTriangle.py
cd rightTriangleChecker.py
cd rightTriangleChecker
python rightTriangle.py
cd rightTriangleChecker
python rightTriangle.py
cd rightTriangleChecker
python rightTriangle.py
cd rightTriangleChecker
python rightTrianly.py
python rightTriangle.py
python song.py
cd ../
cd 99Bottles
cd bottleSong
cd variantOf21
